# ============================================================
# SmartSense Development Environment
# ============================================================
#
# Usage:
#   docker-compose -f docker-compose.dev.yml up -d
#
# This runs only infrastructure services (DB, MQTT)
# Backend should be run locally: cd backend && npm run start:dev
# Frontend (optional): cd frontend && npm run dev
#
# ============================================================

services:
  # ========================================
  # PostgreSQL with TimescaleDB Extension
  # ========================================
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: smartsense-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-smartsense}
      POSTGRES_USER: ${POSTGRES_USER:-smartsense}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      TZ: Asia/Seoul
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - smartsense-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-smartsense}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================================
  # Mosquitto MQTT Broker
  # ========================================
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: smartsense-mqtt-dev
    restart: unless-stopped
    ports:
      - "${MQTT_PORT:-1883}:1883"
      - "${MQTT_WS_PORT:-9001}:9001"
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-dev-data:/mosquitto/data
      - mosquitto-dev-log:/mosquitto/log
    networks:
      - smartsense-network
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -t '$$SYS/#' -C 1 -i healthcheck -W 3"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ========================================
  # Backend API (NestJS) - Built from source
  # ========================================
  smartsense:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartsense-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://smartsense:changeme@smartsense-db-dev:5432/smartsense
      MQTT_BROKER_URL: mqtt://smartsense-mqtt-dev:1883
      OLLAMA_URL: http://ollama
      FIREBASE_PROJECT_ID: hwida-example
      FIREBASE_CLIENT_EMAIL: firebase-adminsdk-fbsvc@hwida-example.iam.gserviceaccount.com
      FIREBASE_PRIVATE_KEY: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCzw7/mxV3R3C+P\nJfY+6XYOLrvrtykAyEC77xqUY3OcrlCOcrYiU+rLZ4yo16qcbYxUsuxmlhVl08lI\n3zMcdaD8VKzwudcGyUbBtfTgbCjnbmh2bweIjQRRDQh1E+csDS0/j9ALznwUJv+O\nNaJ2znGu001geW0dNOLMAehFjL0vXjY2UAjIfQEXDOdn+SZTgk1AZxAjzN8gXst4\n7BmZM3LqdtVSYWm6mbYOqkYJtJNjYT9M/48TOYXCcLdv3CKUCoK13Al3edo2x6gs\ng9JrwOC9TuQKhg29TGNVyK7nUUYwa0dH2i6AJc/22DdQq7G/oQRebL13erE45roE\nSwI13jXnAgMBAAECggEASDQ6esNQrU/vDGTXlSppwEWWNpYBkq5cjf/6oZqWn9rG\nQYkizgP93Yhwj4rcnOtFf+nEGWp0Gsvn3+zC104KBQAv3JsQmsmysXDX9GKNRXPr\n4pIzKO5XSwTcnkYJxwBd6ddmXa+o1+FYKXMyl9zQ/cMio7ryEFajOAUWGgVvIbxd\nvItkhQ9eU/hMNE+qNw+RZ2nYOio+f+ikKFffMnEH0aC7BLFSw2uJiyyVnHKnIqOv\nntDW9liFS7CqJbYHCmkLvQ3hfj+tPHu5g0JbhBB/jOq69LZFaMegdCIgspA+yd9G\nzFADvzEXGITrGOLjlhJRPSyfnpkjEwBT0x+TdTNHIQKBgQDfDSgE29cE0IZL62KA\nlqTsL7Rq4SdIQJ7bBwLHHGMVFcmHiUUsSl8AXbFdI/ONLBwCBFnTHII9YCpA/lzS\nH8XAhTkLu/EMQxGel8WJJ+nDK4cRhBDALTH4rWDAZxiRZuMZVa9IZDzmgCu5NSZj\nSr3ncSWdk70RsC3J8LNuuKZ/hwKBgQDOUazF0e86BaSrxTeX8f7Qh7xydz2gOmbB\nDLJV+JGx86fspsqzLG6w5kyGGW+ND97p57oYkxT6dEbh5xFdOBLs6V6fdKflXR4U\n/SElACws6CbZGZj4AqBPa4aXge3HvEzdN3TLesQB0HTM5w78VnpA3wCtdhoLYngw\nfxSNocRuoQKBgEDRjPCkhj6y7mP/mldt761nS5HHrmezx7Y0ulzsZerJsw/9FyoA\nzszHbXR4rx02VUlMxGGyJjL50C2k/Ypei1QgIuzDCBCdKPCigFgUTj1WV+ECNO/z\n8lKm57fh/eS7NoG1QcPSxVPiqVIgHPC71qX8XocFWOtb/GJz3WDurgvfAoGBAKJI\ncgqjp3TPDYiitqjIizLBIYQzsICAj2RXtUqUGx2K1tH5G8U1NNfmPdjY1vpwuljn\nkWRVBJI/taVo2CqnuZMpuOjZnFp4FPpTZKey7AxiinQHg1/IyQnPPO2dIEgUH619\nOlv284etzMGDGTF4X+74uZK3K6M6z+jtfGAvFtAhAoGAB4Pw2v2soCMvMncUTQ+2\ndkeLaG5H67ZwZRnuAte5SIamf3F9slGALDJug7rv9PELMAu640CWSDG7iph1z7kM\ndjB3RxCqvPCZF2C4UoLrSxKmbmOW8wr8Lpj1Md67tBbwNMyHFmCO/8Px7+LFG/cP\nVLMujn3pBz3vQoTQ1mwT6zg=\n-----END PRIVATE KEY-----\n
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    networks:
      - smartsense-network
networks:
  smartsense-network:
    driver: bridge
    name: smartsense-network-dev

volumes:
  postgres-dev-data:
    name: smartsense-postgres-dev
  mosquitto-dev-data:
    name: smartsense-mosquitto-dev-data
  mosquitto-dev-log:
    name: smartsense-mosquitto-dev-log
